framework:
  secret: '%env(APP_SECRET)%'

#  # session configuration for legacy PHP session
#  session:
#    name: PHPSESSID                     # has to match exactly with legacy cookie name
#    #storage_factory_id: session.storage.factory.native
#    handler_id: null
#
#    storage_factory_id: session.storage.factory.php_bridge
#    #handler_id: session.handler.redis    # use redis instead of file
#
#    cookie_secure: auto
#    cookie_samesite: lax
#    gc_maxlifetime: 3600
